#!/usr/bin/env python
# -*- coding: utf-8 -*-

# (c) Christopher Down 2011
# See the COPYING file for copyright information.

from sys import argv, exit, stderr

if ( len(argv) < 2 ):
    print >> stderr, 'Usage: ' + argv[0] + ' battery'
    exit(1)

files = {
    'charge_full':open('/sys/class/power_supply/' + argv[1] + '/charge_full', 'r'),
    'charge_now':open('/sys/class/power_supply/' + argv[1] + '/charge_now', 'r'),
    'status':open('/sys/class/power_supply/' + argv[1] + '/status', 'r'),
    'present':open('/sys/class/power_supply/' + argv[1] + '/present', 'r'),
}

battery = {
    'charge_full':int(files['charge_full'].read()),
    'charge_now':int(files['charge_now'].read()),
    'status':files['status'].read(1),
    'present':int(files['present'].read()),
}
           
battery['charge_percent'] = battery['charge_now'] * 100 / battery['charge_full']
battery['charge_graphic'] = ''

if ( battery['present'] == 0 ):
    battery['charge_graphic'] = 'MMMM'
else:
    for i in range(0, 100, 25):
        if ( battery['charge_percent'] > i ):
            battery['charge_graphic']+='#'
        else:
            battery['charge_graphic']+='-'

print '[%(charge_graphic)s] %(charge_percent)s%(status)s' % battery
