.TH CELLOUT 1
.SH NAME
cellout \- battery status printer

.SH SYNOPSIS
.B cellout
.RB [ -g ]
.I battery

.SH OPTIONS
.TP
.B -g
Print graphical progress bar.

.SH ARGUMENTS
.TP
.I battery
The battery ID, as shown in /sys/class/power_supply.

.SH BUGS
Some versions of awk interpret \-g as an option to the interpreter rather than
the script. To avoid this, notify your awk interpreter that there are no more
interpreter options with \-\-, or your interpreter's equivalent.

Please report any bugs at https://github.com/cdown/cellout/issues.

.SH AUTHORS
Chris Down <chris at chrisdown dot name>
Dave Reisner <d at falconindy dot com>
